version: "3.9"
services:
  loadbalancer:
    build: ./load_balancer
    ports:
      - "5000:5000"
    networks:
      net1:
        aliases:
          - loadbalancer

  server1:
    build: ./server
    container_name: Server1
    environment:
      - SERVER_ID=Server1
    networks:
      net1:
        aliases:
          - Server1

  server2:
    build: ./server
    container_name: Server2
    environment:
      - SERVER_ID=Server2
    networks:
      net1:
        aliases:
          - Server2

  server3:
    build: ./server
    container_name: Server3
    environment:
      - SERVER_ID=Server3
    networks:
      net1:
        aliases:
          - Server3

networks:
  net1:
