version: '2.39'

services:
  loadbalancer:
    build: ./loadbalancer
    image: loadbalancer
    container_name: loadbalancer
    ports:
      - "5000:5000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    privileged: true
    networks:
      - net1

networks:
  net1:
    external: true
